### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall23#1]
Hi everyone -

I thought I'd kick things off with a post where everyone can reply with an introduction to themselves so we can get to know each other.

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Orange, MA. 

In addition to this course, I also teach [CSCI E-15](https://hesweb.dev/e15). In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. Independently, I do private consulting and share free web development guides and videos via https://codewithsusan.com.

More about my background here: [susanbuck.net](https://susanbuck.net/)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by apoltoratskyi** [comment]
Hello Everyone!
My name is Andrii, Im a software quality engineer. Living in LA, CA. I work with web projects and have some basic knowledge of PHP as well as HTML and JS. Cant wait to dive deeper in to PHP programming.
Glad to be here!

**Comment by richiecarey** [comment]
Hello everyone,

I'm Richie, a web developer working remotely in Massachusetts. At my day job, I work with the Drupal content management system, primarily on the frontend side. I'm happy to be here to level up with modern PHP development, with the goal of working with Laravel in CSCI E-15 next spring.

Wishing you all a great semester!

**Comment by AlexCosta2023** [comment]
Hey everyone,

My name is Alex Costa and I'm the IT Support Manager at the Harvard Kennedy School. Basically signed up to this course because I am pursuing my Programming Certificate at the Harvard Extension School and I've always wanted to kick off my programming rust and expand on my programming abilities. 

Excited to learn!

- Alex

**Comment by arshannon9** [comment]
Hello all,
My name is Tony, and I'm a postdoc working in the Fellowships and Writing Center for Harvard GSAS. I'm excited to learn more about server-side web development this semester, and hopefully next semester in CSCI E-15 in the spring.

**Comment by madagaluna** [comment]
Hi everyone,
My name is Mary.   A year ago, I found myself with a lot of film footage and a grant obligation to make a documentary, so I took a class through the Extension on Film Making and then another on Editing.  I loved them both.  I am considering pursuing the Digital Media AML. There are a couple of CS requirements - a huge hurdle for me - made even more daunting by reading the impressively techy backgrounds of this cohort.  I'm excited to give it a try and have a website I'd upgrade and tinker with excessively if I develop the skills.  Meanwhile, my 13-minute-long documentary was accepted into a film festival, so if you are in Arlington, MA Oct 5th, check out A Porchfest Journey at the Regent Theatre.  If you are in Belmont this weekend, come to our Porchfest (weather permitting!)   Thanks in advance for all the help on Github!

**Comment by rachel-mcelwain** [comment]
Hi everyone! 

My name is Rachel and I live in Atlanta, GA. I am currently a wedding photographer and videographer while pursuing my ALB in computer science and minoring in digital media design and government at Harvard Extension. As of right now I am set to graduate in May! Yay! My reason for taking this class is to actually expand my business in the future. I hope to either create a service for brides with a website or to expand my company to creating websites for anyone while also being able to provide photos and videos of their products. We shall see what the future holds!

**Comment by goodguygg** [comment]
Hi,
My name is Greg, I run a web3 consulting company. I am here to pick up PHP and add it to my tech stack.

**Comment by jrice2023** [comment]
Hi everyone,

I’m Jen and I live in Centerville, MA. I received my undergraduate degree from UMiami and now I’m pursuing a Digital Media graduate degree through the Harvard Extension School. I currently work at HBS Online and I'm taking this class to broaden my skill set. Looking forward to a great semester with you all!

**Comment by ShakRowB** [comment]
Hello, I'm Shakara. 

I'm a data analyst currently working at a non-profit. I'm on a mission to broaden my skill set by pursuing a programming certificate, with the aim of unlocking new career opportunities. This is my last elective, Yay! :)

**Comment by logankilpatrick** [comment]
Hey all! My name is Logan Kilpatrick and I lead developer relations at OpenAI, supporting people using our API and ChatGPT to build some really cool stuff. I have taken some other web dev classes but never Php. I am excited to pick it up and learn. More generally, I have always found that learning new languages and frameworks really does help me be a better engineer so I am excited for this semester.

**Comment by nolinanna** [comment]
Hello!

I'm Anna Nolin. I am an administrator at the Center for Astrophysics at Harvard. I do minimal web development (HTML/CSS) as part of my job, and I'm very interested in learning more to better help my team. My background is mainly artistic - I have worked as a concept artist and done freelance illustrations and other work over the years. Very happy to be here!

**Comment by MNT-348** [comment]
Hello! My name is Minh, and I am a HES student participating from Charlottesville, VA. 

I'm an RN. I have dabbled in Standford's Code in Place, and that has led me to want to explore more CS and adjacent interests. I'm currently taking courses (like this course and CS50 this semester) and am looking to learn some deeper CS and development skills through my HES academic career. I'm comfortable with computers and tech in general as an end-user, but am fairly new to considering the deeper workings and practical under-the-hood utilities I've previously taken for granted. I'm excited to learn what I can, and see how I can apply it in my day job and personal life!

**Comment by dpurser-dev** [comment]
Hi everyone
My name is David. I am an ALM candidate from Melbourne, Australia. 
Looking forward to diving in and learning more about PHP!

**Comment by Abisg** [comment]
Hi class!
I'm Abigail and I live in Florida. I'm in the digital media program with front-end experience. It will be an exciting adventure learning PHP and markdown. 
Nice meeting you all virtually! :)

```
P.S. Code blocks will be my best friend now 
```

**Comment by alilienfeld** [comment]
Hi all,
I'm Ali and I live in New Hampshire. I work remote doing a hybrid of product management and technical support. I am taking this course to learn more about coding in general towards the programming certificate. Looking forward to working with everyone.
