### ISSUE TITLE
Form notes not found in notes navigation sidebar

### ISSUE THREAD

**Issue by nolinanna** [susanBuck/e2-fall23#12]
Hello!

This is a small thing, but I noticed that the PHP Form Notes sections aren't appearing on the navigation sidebar in the [Notes site](https://hesweb.dev/e2/notes/php/form-flow). I wasn't sure if this was just an issue on my end or not! 

![Screenshot 2023-10-15 at 13-52-21 Notes php_form-flow](https://github.com/susanBuck/e2-fall23/assets/101819040/70419063-5db2-490a-acb3-a76ca0ed87a3)

**Comment by susanBuck** [comment]
Fixed! I had forgotten to push my latest changes with the updated table of contents.

Thanks for drawing this to my attention. 👍
