### ISSUE TITLE
Project 1 share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall23#15]
Hi everyone,

In this thread, I'd like you all to check out each other's Project 1s as an opportunity to explore outside code.

To kick things off, below are a few excellent projects to pick from:

**Matching Pennies:**
+ http://e2p1.hesdgmde2.me
+ https://github.com/MNT-348/e2/tree/main/p1

**Tic Tac Toe:**
+ http://e2p1.hesprojects.xyz
+ https://github.com/ShakRowB/e2/tree/main/p1

**War card game:**
+ http://e2p1.dpurser.me
+ https://github.com/dpurser-dev/e2/tree/main/p1

Check out the app and then look through the code and make notes on any of the following:
+ Are there any parts of the code that you found interesting or taught you something new? 
+ Do you have any notes for improvement?
+ Are there any parts of the code that you don't understand? 
+ Are there any built in PHP methods that were used that you hadn't yet encountered? Explain what the method is and what it does.
+ Anything else that sticks out to you...

**Reply to this thread with your notes, and also include a link to your project on your server and in Github.**

**When coming to this thread, pick a project that has not already been responded to, pulling from the replies that come in.**

**Comment by madagaluna** [comment]
Here's my project 1 before refactoring and using ternary for the if else.  And before fixing the layout,

<?php

## Game planning
// initalize an array to hold results
$results = [];
for ($i = 1; $i <= 10; $i++) {
    // initalize an array called schedule
    $schedule = [];
    // Create an array of available performance times
    $times = [1,2,3];

    // For Performer A, randomly choose a time to perform:
    $performerA_time = $times[array_rand($times)];
    //add performer A's time to the schedule
    $schedule[] = $performerA_time;
    // For Performer B, randomly choose a time to perform:
    $performerB_time = $times[array_rand($times)];
    // compare performer B's time to performer A's time to see if time is available
    if ($performerB_time != $performerA_time) {
        // if the time is available, update schedule to include PB
        $schedule[] = $performerB_time;
    }
    // else update schedule that The Bars will not be performing
    else {

        $schedule[] = "that's it: Wah-Wah is not just a pedal. The Bars will not be a performing today.";
    }

    // concatenate the schedule and make it a string https://www.w3schools.com/php/func_string_implode.asp
    $schedule_String =  implode(" and ", $schedule);
    //show results

    $results [] = [
     'the_Foos_time' => $performerA_time,
     'the_Bars_time' => $performerB_time,
     'the_Schedule_is' => $schedule_String,
    ];
}
require 'index-view.php';

**Comment by susanBuck** [comment]
Hi @madagaluna - For some reason your code is being truncated here. Could you link to your project in Github so classmates can see the "full picture" ? Also include a link to your application on your server.

I also had a mistake in my original post where I forgot to include the sampling of 3 projects you can pick from to peer review. That's been updated now.

**Comment by madagaluna** [comment]
I wasn’t sure what we were supposed to do. I didn’t really want to share my code, but I wanted to get the ball rolling.  I’ll just pull mine so folks focus on the examples.  Thanks!

Sent from my iPhone

On Oct 25, 2023, at 11:51 AM, Susan Buck ***@***.***> wrote:

﻿

Hi @madagaluna<https://github.com/madagaluna> - For some reason your code is being truncated here. Could you link to your project in Github so classmates can see the "full picture" ? Also include a link to your application on your server.

I also had a mistake in my original post where I forgot to include the sampling of 3 projects you can pick from to peer review. That's been updated now.

**Comment by madagaluna** [comment]
https://github.com/madagaluna/e2/tree/main/p1

http://e2p1.timberthedestroyer.xyz/

Really fun and creative game, Minh!  It reads very logically.   I’m wondering what functions, if any, you created for the defactoring assignment and if you were able to apply the ternary (approach?) to the if/else statement in the while loop.  I like that you applied the echo php island in your list- were we doing that way back then?  All in, very impressive and I couldn’t agree with you more about how daunting CS50 is.   Although I am on the struggle bus in this class as well I very much appreciate how well organized and clear all the explanations are - and the assignments are well thought out  to get some basic concept down efficiently (funny story:  in P1 I learned about the implode function to concatenate and change an int to a string .  … in P2 I realized if I used “” I didn’t need to switch type - it was a string all along- the hours I spent!  Did I mention the bus?) When I am a little less fried, I’ll spend more time looking at the code.  It’s helpful!

**Comment by madagaluna** [comment]
http://e2p1.timberthedestroyer.xyz/

https://github.com/madagaluna/e2/tree/main/p1

Notes on the examples coming soon(ish) ....

**Comment by richiecarey** [comment]
----

**(Similar to the card game) War**

http://e2p1.careyinternet.com/

https://github.com/richiecarey/e2/tree/main/p1

----

**Tic Tac Toe**

@ShakRowB  .. very nice job, well organized .. the `check for wins` loop is impressive .. I'm unsure if the global `$game_board` array is necessary on lines 6 - 10 as the array is initialized and set inside the while loop .. excellent work overall!

----

**Going to Boston**

@nolinanna .. looks excellent .. well commented and structured .. the `do..while` loop was a good choice .. I'm wondering if there may be ways to move more of the text snippets out of `index.php` into `index-view.php` or maybe group them together more  .. I struggled with that a bit and ended up using an array like `$outcome = ['tie', 'player one', 'player two'];` at the top of index.php to sort of keep more of those snippets together .. but I'm not sure about that choice either :-)

----

Great work everyone!

----

**Comment by AlexCosta2023** [comment]
[http://e2p1.alexandercosta.net/](http://e2p1.alexandercosta.net/)

[https://github.com/AlexCosta2023/e2/tree/main/p1](https://github.com/AlexCosta2023/e2/tree/main/p1)

**Simple game of 20-Sided Dice Roll.**

**Comment by MNT-348** [comment]
> https://github.com/madagaluna/e2/tree/main/p1
> 
> http://e2p1.timberthedestroyer.xyz/
> 
> Really fun and creative game, Minh! It reads very logically. I’m wondering what functions, if any, you created for the defactoring assignment and if you were able to apply the ternary (approach?) to the if/else statement in the while loop. I like that you applied the echo php island in your list- were we doing that way back then? All in, very impressive and I couldn’t agree with you more about how daunting CS50 is. Although I am on the struggle bus in this class as well I very much appreciate how well organized and clear all the explanations are - and the assignments are well thought out to get some basic concept down efficiently (funny story: in P1 I learned about the implode function to concatenate and change an int to a string . … in P2 I realized if I used “” I didn’t need to switch type - it was a string all along- the hours I spent! Did I mention the bus?) When I am a little less fried, I’ll spend more time looking at the code. It’s helpful!

Thank you for your kind words, Mary!
I actually didn't create any function for refactoring since there really wasn't much to encapsulate as such (since as written, the script rolls mostly just through the loop with built-in `rand()` until it's done). I did make some code more concise with what we learned at least. I was also able to at least add a ternary operator at the end which made it look neater:
```
# Print win states after a player has no more HP/coins
$winner = ($p1Coins == 0) ? $player2 : $player1;
$loser = ($p1Coins == 0) ? $player1 : $player2;
```
Best of luck with P2 and CS50!

Edit (to add my reply; I was not in a position to do so previously): 
Your game simulation is very interesting! I'm impressed because of how unorthodox (in a good way!) it is, since it isn't a traditional game or like one listed on the examples for P1.  It makes excellent logical sense for what you've done, since it applies checking the randomized values of the performance times. Good for you for the confidence to think outside of the box and create a working product! That's an example for the mindset I should take in this course and CS50; the fear of hitting roadblocks in code is creating a psychological barrier, but it's not going to get any better if I don't practice code!

**Comment by nolinanna** [comment]
**Going to Boston (Dice Rolls)**

- http://e2p1.nolinanna.me/
- https://github.com/nolinanna/e2/tree/main/p1

**Notes for R. Carey**

> (Similar to the card game) War
> http://e2p1.careyinternet.com/
> https://github.com/richiecarey/e2/tree/main/p1

**Are there any parts of the code that you found interesting or taught you something new?**
Your presentation was really nice! And your code itself was so clear and easy to follow. I'm new to programming, so seeing the way you broke it down was helpful, specifically in seeing how foreach and different arrays can eliminate redundancy. 

**Anything else that sticks out to you...**
Great job!! Your project execution is something to aim for in future projects.

**Comment by rachel-mcelwain** [comment]
http://e2p1.rachelmhes.me/
https://github.com/rachel-mcelwain/e2/tree/main/p1 

Impressive work on the tic tac toe game! I definitely learned a lot reading the code for it and I found the set up for the game pretty interesting. The layout for the 9 squares being set up and the written code putting the game to action was definitely a learning experience for me. Awesome job!

**Comment by ShakRowB** [comment]
> **(Similar to the card game) War**
> 
> http://e2p1.careyinternet.com/
> 
> https://github.com/richiecarey/e2/tree/main/p1

Great work, Richie! The concept of using actual icons as array values is quite interesting. I'm not entirely convinced it's the most optimal approach, though. Perhaps it might be easier to use values or strings to represent each item, and then incorporate the icon in the view. Nevertheless, good job!

**Comment by ShakRowB** [comment]
> http://e2p1.rachelmhes.me/ https://github.com/rachel-mcelwain/e2/tree/main/p1
> 
> Impressive work on the tic tac toe game! I definitely learned a lot reading the code for it and I found the set up for the game pretty interesting. The layout for the 9 squares being set up and the written code putting the game to action was definitely a learning experience for me. Awesome job!

Thank you! You should see p2. LOL. Totally took me for a loop, pun intended.

**Comment by MNT-348** [comment]
> **War card game:**
> 
>     * http://e2p1.dpurser.me
> 
>     * https://github.com/dpurser-dev/e2/tree/main/p1

David, I have to admit, I want to thank you for this code as an example. I was so confused on how to get cards implemented, and figured it was a pre-loaded library of some sort that I didn't know about (though there perhaps exists one). Your way of implementing it via code and suit symbols is quite elegant and I wish I had the logical sense to have thought that could be a way to implement them. I'm definitely very impressed on the loops you used to create the suits and face cards!

Your project code overall (on the index.php) is quite advanced for me (I've not truly used HTML or PHP before this course, only half-dabbling in the Odin Project and unfortunately not completing it), but it's very clean at the very least, and I'm definitely going to study it so I can understand what's going on further. This is great work!

**Comment by goodguygg** [comment]
https://github.com/goodguygg/e2/tree/main/p1
http://e2p1.grgharv.bio/

Good job y'll very impressive!

**Comment by alilienfeld** [comment]
http://e2p1.hesclassali.me/
https://github.com/alilienfeld/e2/tree/main/p1

Awesome projects everyone!

**Comment by arshannon9** [comment]
http://e2p1.anthonyrshannon.me/
https://github.com/arshannon9/e2/tree/main/p1

I tried my hand at a War game, and I think it came out pretty well (save for some SoC faults w.r.t. the implementation of the results table).

Nice projects all around!

**Comment by Abisg** [comment]
Hi all! I love all of your projects! 

I did a word-guessing game:)

[http://e2p1.abihes.me/](http://e2p1.abihes.me/)
[https://github.com/Abisg/e2/tree/main/p1](https://github.com/Abisg/e2/tree/main/p1)

**Comment by anp2937** [comment]
**Tic Tac Toe:**

http://e2p1.hesprojects.xyz/
https://github.com/ShakRowB/e2/tree/main/p1

@ShakRowB I like your project. Very good job! When I reviewed it I found some places could be done differently:

_Index.php_  - Lines 15-16 :
Consider using `list($playerA, $playerB)` function instead.


_Index.php_  - Lines 92-97:

```
        // Switch to the next player's turn if no win
        if ($player == $playerA) {
            $player = $playerB;
        } else {
            $player = $playerA;
        }
```
Correct me if I wrong, **else**  condition is probably redundant here since you defined your $playerA and $playerB earlier in code.


_Index.php_  - Lines 114-121:

```
    // Increment number of rounds played, and define the winner for the game depending on player wins variables 
    $rounds++;
    if ($playerAWins > $playerBWins) {
        $gwinner = "Player A";
    }
   else {
        $gwinner = "Player B";
    }
```

What about the case when $playerAWins == $playerBWins ?

Have you consider using an array with winning combinations? So you can compare each combination against your current board state.
```
const winningCombinations = [
    // Rows
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],

    // Columns
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],

    // Diagonals
    [0, 4, 8],
    [2, 4, 6]
];
```
Looks much more cleaner to me.

------------------------------------------

Here is my project (**Blackjack** card game):

http://p1.anphp.me
https://github.com/anp2937/e2/tree/main/p1

**Comment by ShakRowB** [comment]
> **Tic Tac Toe:**
> 
> http://e2p1.hesprojects.xyz/ https://github.com/ShakRowB/e2/tree/main/p1
> 
> @ShakRowB I like your project. Very good job! When I reviewed it I found some places could be done differently:
> 
> _Index.php_ - Lines 15-16 : Consider using `list($playerA, $playerB)` function instead.
> 
> _Index.php_ - Lines 92-97:
> 
> ```
>         // Switch to the next player's turn if no win
>         if ($player == $playerA) {
>             $player = $playerB;
>         } else {
>             $player = $playerA;
>         }
> ```
> 
> Correct me if I wrong, **else** condition is probably redundant here since you defined your $playerA and $playerB earlier in code.
> 
**Probably, i'd have to test it.** 

> _Index.php_ - Lines 114-121:
> 
> ```
>     // Increment number of rounds played, and define the winner for the game depending on player wins variables 
>     $rounds++;
>     if ($playerAWins > $playerBWins) {
>         $gwinner = "Player A";
>     }
>    else {
>         $gwinner = "Player B";
>     }
> ```
> 
> What about the case when $playerAWins == $playerBWins ?
> 
**I don't believe it matters in this condition. That as a possibility is not relevant to the status of wins in the game. If I win a round, and then the computer wins a round, nothing happens and the game continues till the next where one has 2, and then ends**

> Have you consider using an array with winning combinations? So you can compare each combination against your current board state.
> 
> ```
> const winningCombinations = [
>     // Rows
>     [0, 1, 2],
>     [3, 4, 5],
>     [6, 7, 8],
> 
>     // Columns
>     [0, 3, 6],
>     [1, 4, 7],
>     [2, 5, 8],
> 
>     // Diagonals
>     [0, 4, 8],
>     [2, 4, 6]
> ];
> ```
> 

**Yes, I have but I believe this is simpler.** 

> Looks much more cleaner to me.
> 
> Here is my project (**Blackjack** card game):
> 
> http://p1.anphp.me https://github.com/anp2937/e2/tree/main/p1

**Nice!**
