### ISSUE TITLE
PHP CS Fixer: executablePath not found.

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall23#17]
I'm creating this thread to discuss the issue described here: https://github.com/susanBuck/e2-fall23/issues/14#issuecomment-1776572222:

> I also have some issues with making this extension work properly. I installed both client/server versions on extension and when saving the file on Mac with Command+S I receive this error:

> PHP CS Fixer: executablePath not found. Try setting "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar" and try again.

> Basically I just installed these extensions from the Visual Studio code and did not perform any additional configuration.
Looks like this is something very trivial but I was not able to find the solution. Hope someone from the class had the same issue and found the solution. -[anp2937](https://github.com/anp2937)

I'm looking into this issue now and will reply again shortly with more details.

**Comment by susanBuck** [comment]
@anp2937 -

Can you add the following to your settings and report back if that fixes the issue for you?

```
"php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
"[php]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "junstyle.php-cs-fixer"
}
```

**Comment by anp2937** [comment]
Thank you @susanBuck.
It works like a charm.
Just to save others some time - here is the path to config file on the server where you need to update configuration.

`/root/.vscode-server/data/Machine/settings.json`

**Comment by susanBuck** [comment]
Thanks for that extra tip @anp2937 

Also if anyone needs a refresher on working directly in the settings.json file revisit the [Week 1, Part 6](https://www.youtube.com/embed/akVeTIXSz4o?rel=0&showinfo=0) video starting at the 12:19 mark.
