### ISSUE TITLE
Issue with DigitalOcean

### ISSUE THREAD

**Issue by rachel-mcelwain** [susanBuck/e2-fall23#18]
I have posted a picture. I am not sure what went wrong when I created a new folder for e2p2. I followed step by step to the video and I am unsure why this comes to my result instead of my work. 
<img width="1440" alt="Screen Shot 2023-10-25 at 5 25 17 PM" src="https://github.com/susanBuck/e2-fall23/assets/90016782/2eda8466-e02e-490b-8e6a-c74dce419d7d">

**Comment by anp2937** [comment]
Have you added new vhost config file under `/etc/nginx/sites-available` ?
Have you created a simlink of site-available config to site-enabled. `ln -s /etc/nginx/sites-available/p2 /etc/nginx/sites-enabled` ?  
Do not forget to restart nginx after all these actions `systemctl restart nginx` .

**Comment by susanBuck** [comment]
I agree with @anp2937's suggestions that perhaps a step was missed with setting up the subdomain.

However, note that the way I outlined setting up subdomains was to put all your configs in a single file `/etc/nginx/sites-available/hes`, which only needs to be simlinked once.

You could create separate config files for each subdomain, but just wanted to point out that's not the approach I showed - just to avoid any confusion.

I just loaded http://e2p2.rachelmhes.me/ and it seems to be working now so I'm assuming you sorted it out. : )

**Comment by rachel-mcelwain** [comment]
It is not working on my end, I still get the same message as before. I have no idea why it is showing up on your end when you load it and I am still getting the SSH key issue on my end. Please help, I have tried everything

**Comment by susanBuck** [comment]
@rachel-mcelwain - Can you try a different browser and see if it works there? It could be a caching issue.

Also, can you describe in more detail the SSH key issue?

**Comment by rachel-mcelwain** [comment]
It must be a catching issue, because it is working just fine on chrome. Very annoying issue!

**Comment by susanBuck** [comment]
Glad that sorted it out! If you clear your cache on the original browser you were trying to view it with, that may resolve the issue there.
