### ISSUE TITLE
Sub Domain issues

### ISSUE THREAD

**Issue by goodguygg** [susanBuck/e2-fall23#19]
I have followed the instructions and created the hes file in the 
/etc/nginx/sites-available/hes
here are the contents of this fille
server {

    listen 80;
    server_name e2p1.grgharv.bio;
    root /var/www/e2/p1/;

    index index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

server {

    listen 80;
    server_name e2p2.grgharv.bio;
    root /var/www/e2/p2/;

    index index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
then I have ran the commands as instructed
root@php-class:~#ln -s /etc/nginx/sites-available/hes /etc/nginx/sites-enabledd
ln: failed to create symbolic link '/etc/nginx/sites-enabled/hes': File exists
root@php-class:~# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@php-class:~# systemctl restart nginx

But the subdomain still does not work, and the main domain shows project 1

**Comment by goodguygg** [comment]
Also the ssh keeps freezing and I keep having to reboot the drop to use it

**Comment by susanBuck** [comment]
Hi @goodguygg -

Is this a server you're using just for this course? If so, can you grant me access [via these instructions](https://hesweb.dev/e2/notes/infrastructure/servers-config#instructor-server-access) so I can help you troubleshoot?

**Comment by goodguygg** [comment]
yes, will do right now

**Comment by goodguygg** [comment]
Also worth mentioning that I just configured domain records like 10 min ago

**Comment by goodguygg** [comment]
Done, your authorized key is now there, my ip is 104.248.194.225

**Comment by susanBuck** [comment]
Having a hard time SSH'ing in - it gets hung up or returns this error:

```
kex_exchange_identification: read: Connection reset by peer
Connection reset by 104.248.194.225 port 22
```

Are these the same symptoms you're seeing when you said the SSH keeps freezing?

Can you confirm you [enabled a swap file](https://hesweb.dev/e2/notes/infrastructure/servers-config#enable-swap-file)? VSCode SSH is resource intensive and without a swap file on our budget servers, you'll see performance issues.

**Comment by goodguygg** [comment]
doing this right now

**Comment by goodguygg** [comment]
Done
root@php-class:~# sudo swapon -s
Filename				Type		Size		Used		Priority
/swapfile                               file		4194300		186172		-2
root@php-class:~#

**Comment by susanBuck** [comment]
Ok, I was able to log in. Looking at the subdomain issue now.

**Comment by goodguygg** [comment]
Thank you

**Comment by susanBuck** [comment]
http://e2p1.grgharv.bio and http://e2p2.grgharv.bio both appear to be working as expected.

The reason http://grgharv.bio is defaulting to your p1 is because you commented out the default server config in `/etc/nginx/sites-available/digitalocean` for the root domain:

```

# server {
# 	listen 80 default_server;
# 	listen [::]:80 default_server ipv6only=on;

# 	root /var/www/html;
# 	index index.php index.html index.htm;

# 	# Make site accessible from http://localhost/
# 	server_name localhost;

# 	location / {
# 		# First attempt to serve request as file, then
# 		# as directory, then fall back to displaying a 404.
# 		try_files $uri $uri/ =404;
# 		# Uncomment to enable naxsi on this location
# 		# include /etc/nginx/naxsi.rules
# 	}

# 	error_page 404 /404.html;
# 	error_page 500 502 503 504 /50x.html;
# 	location = /50x.html {
# 		root /usr/share/nginx/html;
# 	}

# 	location ~ \.php$ {
#         include snippets/fastcgi-php.conf;
#         fastcgi_pass unix:/run/php/php8.0-fpm.sock;
# 	}

# 	# deny access to .htaccess files, if Apache's document root
# 	# concurs with nginx's one
# 	#
# 	#location ~ /\.ht {
# 	#	deny all;
# 	#}
# }
```

If you bring back those lines and restart nginx, visiting http://grgharv.bio should load `/var/www/html/index.html`

**Comment by goodguygg** [comment]
Trying again, the http://e2p2.grgharv.bio/ works as expected, http://e2p1.grgharv.bio/ is still down when I try to access it

**Comment by susanBuck** [comment]
Could be a caching issue. Can you try http://e2p1.grgharv.bio/ on a different browser? If it works in a different browser, try clearing your cache in your original browser and see if that resolves the issue.

For reference, here's what I see on my end: 
<img width="846" alt="image" src="https://github.com/susanBuck/e2-fall23/assets/237711/01d3faba-d6d6-44c5-87eb-7c3f155f6010">

**Comment by goodguygg** [comment]
Everything works perfect, thank you so much for your help!
