### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#22]
I am getting a 404 error on the /contact page.  I copied the github code from Susan's repository after hours of looking for a minute syntax error and I am still receiving the same error.  My revised error message is not showing, either.  Any thoughts?

**Comment by anp2937** [comment]
I checked your project https://github.com/madagaluna/e2/blob/main/zipfoods/ and the code looks good.

Check if you correctly configured vhosts **/etc/nginx/sites-available/hes** . Valid config for this project should look like this:

```
server {
    listen 80;
    server_name e2zipfoods.timberthedestroyer.xyz;
    root /var/www/e2/zipfoods/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

**Comment by madagaluna** [comment]
I would have never caught that.  I was looking in the wrong place.  I missed that the server block index and location were different - I was feeling pretty cavalier about setting up server blocks.  Well, let that be a lesson. 

  Thank you!
