### ISSUE TITLE
private function / public function in notes

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#25]
JIC anyone else gets tripped up, I noticed a discrepancy between the video and in the code in the notes for the Products class property.  The notes list the class as private, the video sets the class as public.  Private did not work for me.
<?php
namespace App;
class Products
{
    # Properties
    private $products = [];   <- in the video this is a public, not private.  Private didn't work for me.

**Comment by madagaluna** [comment]
disregard... part 4 explains this

**Comment by susanBuck** [comment]
Apologies for any temporary confusion @madagaluna :)
