### ISSUE TITLE
 TINYINT vs BOOLEAN

### ISSUE THREAD

**Issue by anp2937** [susanBuck/e2-fall23#26]
I noticed that when we created a table 'products' - the last column type was converter to **tinyint(1)**.
<img width="600" alt="Screenshot 2023-11-26 at 10 02 28 PM" src="https://github.com/susanBuck/e2-fall23/assets/131134358/12862742-ff45-491c-b188-da08ac50ecbf">
Previously I thought that BOOLEAN attributes can take only `true` or `false` (or 1 and 0) but I was wrong. According to [MySql Documentation ](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html) this field can store any number from -128 to 127:
TINYINT
`A very small integer. The signed range is -128 to 127. The unsigned range is 0 to 255.`

Interesting...

**Comment by richiecarey** [comment]
This page provides some additional detail ...

https://www.mysqltutorial.org/mysql-boolean/

----

**Summary**

* MySQL uses TINYINT(1) to represent the BOOLEAN type.

* Use the BOOLEAN keyword to declare a column with the BOOLEAN type. The BOOLEAN and TINYINT(1) are synonyms.

* Zero is false while non-zero is true.

**Comment by susanBuck** [comment]
@anp2937 Good observation! Boolean is in fact just an alias to tinyint.
