### ISSUE TITLE
Fatal Error Message on Zipfoods Products Page

### ISSUE THREAD

**Issue by MNT-348** [susanBuck/e2-fall23#28]
Since last week, I've been struggling with the following error when I go to my Products page:
```
Fatal error: Uncaught Error: Call to undefined method App\Controllers\ProductsController::products() in /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php:241 

Stack trace: 
#0 /var/www/e2/zipfoods/public/index.php(16): E2\App->route() 
#1 {main} thrown in /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php on line 241
```

I thought I was following along with the video lectures and associated notes faithfully, but for some reason I can't seem to find out how to fix this error. I checked my index.php and [Professor Buck's Zipfoods code](https://github.com/susanBuck/e2/tree/main/zipfoods), and I can't find my way out since it seems to be the same?

(I'm sorry if I've missed something simple from a previous week that could help me.)

**Comment by anp2937** [comment]
Double-check your **routes.php** file.
According the error you are calling a method `products()` which is not exists in ProductsController

If you follow lecture video and notes - your routes should look like this:
`    '/products' => ['ProductsController', 'index'], `
 `   '/product' => ['ProductsController', 'show'],`


According to your error now you have something like this : `'/products' => ['ProductsController', 'products'],`

Do not forget to post a link to your GitHub repo. It will be easier for others to find a problem and help you to find a solution

**Comment by susanBuck** [comment]
I agree with @anp2937 👍 

Double check your `ProductsController` file has a `products` method as that's what the route is invoking. If the method is named something else in `ProductsController`, update the route accordingly.

**Comment by MNT-348** [comment]
> Double-check your **routes.php** file. According the error you are calling a method `products()` which is not exists in ProductsController
> If you follow lecture video and notes - your routes should look like this: ` '/products' => ['ProductsController', 'index'],` ` '/product' => ['ProductsController', 'show'],`
> According to your error now you have something like this : `'/products' => ['ProductsController', 'products'],`
> Do not forget to post a link to your GitHub repo. It will be easier for others to find a problem and help you to find a solution

That did it! I'm sorry I missed something so simple. I'm not sure how I glossed over that from lecture/notes, but now I can continue! 

Thank you very much!

**Comment by susanBuck** [comment]
@MNT-348 - We've all been there. Sometimes when you stare at something too long you stop "seeing" it. : ) Glad it's sorted out now!
