### ISSUE TITLE
product_id not found

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#30]
I made it the last two minutes of the video, thinking _some_ of the concepts were starting to gel, when I received a "value for product_id cannot be blank" error upon submitting the form.    I added the hidden product_id so I'm not sure where this is coming from.  Any thoughts on where I can look?  TIA!

fwiw: https://github.com/madagaluna/e2/commit/21d76822760ec3ff8fa54b4a76cd35f408e37391

**Comment by anp2937** [comment]
According to your **ProductsController.php** you are trying to save product id to db column "product_id", but at the same time validating "id". Probably that's why validation does not pass.




```
  public function saveReview()
    {
        $this->app->validate([
            'id' => 'required',
            'sku' => 'required',
            'name' => 'required', # Note how multiple validation rules are separated by a |
            'review' => 'required|minLength:200' # Note that some rules accept paramaters, which follow a :
        ]);

...
        $this ->app->db()->insert('reviews', [
          'product_id' => $product_id,
          'sku' => $sku,
          'name' => $name,
          'review' => $review
        ]);
```

**Comment by susanBuck** [comment]
👍 to @anp2937's suggestion. 

The validation feedback I see when testing it says *The value for id can not be blank*. We don't need an `id` field for reviews (just a `product_id` field to associate the review with a product) - the `id` data is generated automatically when the review is inserted into the database.

**Comment by madagaluna** [comment]
Thank you both!
