### ISSUE TITLE
Will the Zipfoods GitHub repository be updated to include database methods?

### ISSUE THREAD

**Issue by dpurser-dev** [susanBuck/e2-fall23#31]
Hi Susan,

I am struggling a bit to integrate the correct approach to using databases into my p3 assignment. 

While I understand the value of releasing the database content incrementally, I am interested in learning the **best** way of storing and retrieving data for our projects. I also understand that this is a bit subjective, so perhaps this question is better asked with respect to the 5 or so unique approaches that we have learned so far - which of these is **best**? The intent behind this question is to make the variety of approaches a bit more manageable from an assignment perspective.

1. Store data in **class constructor method**
2. Store data in a **JSON** file, and retrieve using **class constructor method**
3. Store data in a **database** created using **SQL commands** and retrieve via a **user-defined function**
4. Store data in a **database** created using **SQL commands** and retrieve via **framework methods**
5. Store data in a **database** created using **migrations** commands and retrieve via **framework methods**

I note that the Zipfoods GitHub repository uses **method 2**. However, I doubt that this is the best approach given the more recent content we have learned. If one of the new methods we have learned is better, will the Zipfoods repository be updated as our reference app?

Thanks so much for your help!

David

**Comment by susanBuck** [comment]
Hi @dpurser-dev -

Method 5 is what we're heading towards for all our methods, and the final version of ZipFoods at the end of the semester will reflect that.

For reference, here's the [e2 code repository from the previous semester](https://github.com/susanBuck/e2-fall22-code) that shows what ZipFoods will ultimately look like.

**Comment by dpurser-dev** [comment]
Hi @susanBuck, that's perfect. Thank you for the clarification and link.
