### ISSUE TITLE
PHP 8.2 "Deprecated: Creation of dynamic property is deprecated"

### ISSUE THREAD

**Issue by anp2937** [susanBuck/e2-fall23#32]
I installed the latest PHP8.2 and looks like it does not work properly with our framework.
For example when I submit a review I receive Warnings "Deprecated: Creation of dynamic property is deprecated"
![Screenshot 2023-12-03 at 1 50 49 PM](https://github.com/susanBuck/e2-fall23/assets/131134358/fceb9e2c-b0cc-45b7-8c46-bad26db5b8ac)

What should we usually do in such cases? Since we are not allowed to change anything inside `vendor` directory? Do we need somehow override the App class and then declare our properties in new class?

I switched back to PHP 8.0 for now. So this is just a general question.

**Comment by susanBuck** [comment]
I'll update the framework to address this and report back when it's updated. When it is, you'll just need to run `composer update` to pull in the latest updates.

When this happens in real world contexts, I typically start by going to the package's Github Issues to see if there's discussion of the incompatibility and any plans to update it. A well-maintained package is usually up on these things and will address the issue quickly. 

Another option is you can fork the package and address the issue yourself. I have a video describing that process here: [Composer require a forked repository](https://www.youtube.com/watch?v=fG08dcJ8xFE).

If you know the fix, you can also submit a pull request to the package maintainer and see if they accept it. This way you don't have to create/maintain your own fork and you could be helping out other developers using that package.

It's a good question - as it's definitely something you'll run into when working with outside code!

**Comment by susanBuck** [comment]
Updated the framework to address the deprecation issue. Run `composer update` in any projects using the framework (zipfoods, p3) to grab the latest update.

Let me know if you run into any other issues with the upgrade to PHP 8.2.

**Comment by anp2937** [comment]
@susanBuck , thank you for the quick response. Solution works.
