### ISSUE TITLE
Collecting AppCommand seed functions into seedAll() function

### ISSUE THREAD

**Issue by dpurser-dev** [susanBuck/e2-fall23#34]
Hi Susan,

I just wanted to check, is there an intuitive way to collect all of the seed functions together and execute at once? Seed functions are helpful to keep separated, but I am also finding myself needing to run them all at various intervals in the development of p3. It would be nice to collect them together as well. So far, I have tried the following;

1. Declaring a public function **seedAll()** below all other functions in AppCommand
2. Creating a new Command file called AllCommand, importing the functions from AppCommand, and then collecting in a function called **seedAll()**

Both of these seemed reasonably logical approaches, but neither worked - so I wanted to check, is this possible?

Thank you in advance!

David

**Comment by richiecarey** [comment]
I created a `fresh` public function that calls three other public functions in the same `AppCommand` file, `migrate` to build the tables, `seedGames`, and `seedRounds`. This seems to work as expected to (re)create the tables, and to seed the game and round data.

**Comment by susanBuck** [comment]
Hi @richiecarey -

I support @richiecarey's answer. It replicates what I did in zipfoods with the [fresh](https://github.com/susanBuck/e2/blob/main/zipfoods/app/Commands/AppCommand.php#L21) method:

```php
/**
* Run migrations and all seeds giving a “fresh start“ on the database
*/
public function fresh()
{
    $this->migrate();
    $this->seedProducts();
    $this->seedReviews();
}
```

If you tried this and it didn't work, let me know how it failed (error messages, etc.) and I can take a look and help troubleshoot.

**Comment by dpurser-dev** [comment]
Thanks @richiecarey and @susanBuck , I was just missing the '$this' pointer to my function - I appreciate the help.
