### ISSUE TITLE
Re-installing p3, database already exists

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#35]
I made a change during the p3 set up that I tried to undo from source control but instead I ended up with multiple blank screens. Changing the layout didn't fix it. "Discard Changes" gave a pop-up message that the file would be deleted permanently. Meanwhile, my browser did not show the page (it had earlier).

After monkeying around for too long, I decided to delete and reinstall p3. CREATE DATABASE, prompted: ERROR 1007 (HY000): Can't create database 'p3'; database exists.

Will this previously created p3 database will work with this new p3 installation? I'd hate to get tripped up so early.

TIA!

Mary

**Comment by susanBuck** [comment]
@madagaluna - Yes, the previously created p3 database should work fine. If it doesn't, let me know!

**Comment by madagaluna** [comment]
That's a relief..  Thank you!
