### ISSUE TITLE
HES server and repository 

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#36]
I tried to install an application from my own repository to the digital ocean server.  I did this in tandem with installing p3. P3 worked without a problem (before the reinstall) but my other application did not. Is not being able to install unknown applications by hes design or something this user manifested independently?

This is unrelated to the database question.

TIA

mary

**Comment by susanBuck** [comment]
There's nothing on the server that should prevent unknown applications. 

If you want to provide additional details I'm happy to help you troubleshoot. (E.g. what software is the application using and how is it failing to work?)

**Comment by madagaluna** [comment]
I tried again tonight and I have working application.   It's not what I was aiming for and I'm not sure what happened last night, but that's fine.  There's probably something worth learning there, but not at the moment.  Thanks for the offer!
