### ISSUE TITLE
Trouble seeing p2

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#38]
Hello!  I suspect I am going to have to refer back to p2 while building p3 but I can't seem to pull it up.  When I turned it in, I had made a mistake setting up the server but I double checked and the server set up is correct now.  I made a copy of the application just in case (and restarted nginx).  Neither application are visible.  I'm not sure what's going on ...

TIA!

Mary

Here is the set up code:

```
server {
listen 80;
server_name e2p2.timberthedestroyer.xyz;
root /var/www/e2/p2/public;

index index.php index.html;

location / {
try_files $uri $uri/ /index.php?$query_string;
}

location ~ \.php$ {
fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
include fastcgi_params;
}
}

server {
listen 80;
server_name e2p2.2.timberthedestroyer.xyz;
root /var/www/e2/p2.2/public;

index index.php index.html;

location / {
try_files $uri $uri/ /index.php?$query_string;
}

location ~ \.php$ {
fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
include fastcgi_params;
}
}
```

**Comment by richiecarey** [comment]
I'm wondering if the additional '.' character is creating an issue. To confirm or exclude this as a possibility, perhaps change 'p2.2' to 'p2v2' in both the directory name and the server config and give it another try.

**Comment by susanBuck** [comment]
Hi @madagaluna -

P2 did not use the framework, so instead of setting the root to `/var/www/e2/p2/public` you should just set it to `/var/www/e2/p2/`.

If that doesn't fix things, let us know.

**Comment by madagaluna** [comment]
Good thought @richiecarey, but it was the public setting.  Funny story, I was listening to the set up for p3 (again) while I was monkeying with this and thought to myself, "I'm not sure exactly why we set it to public".  I'm still not 100% clear on this, but I now get that it's not a default - has to do with frameworks ....
