### ISSUE TITLE
test error:  MalformedLocatorException

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#39]
**I get this error:** 
 [MalformedLocatorException] XPath or CSS locator is malformed: [test=1pm-radio] ) 
when I run the first test in the video: 

**My output shows only two steps, listed in reverse order:**
 2. $I->fillField("[test=1pm-radio]","1pm") at tests/Acceptance/P3Cest.php:12
 1. $I->amOnPage("/") at tests/Acceptance/P3Cest.php:11

#1  Codeception\Lib\InnerBrowser->fillField
#2  /var/www/e2/p3/tests/Support/_generated/AcceptanceTesterActions.php:7463
#3 /var/www/e2/p3/tests/Acceptance/P3Cest.php:12
#4  Tests\Acceptance\P3Cest->playGame
#5  /var/www/e2/p3/vendor/bin/codecept:119
Artifacts:

Html: /var/www/e2/p3/tests/_output/Tests.Acceptance.P3Cest.playGame.fail.html
Response: /var/www/e2/p3/tests/_output/Tests.Acceptance.P3Cest.playGame.fail.html

 I've looked at this for a quite a while and read some forums and still, I have no idea where the issue is coming from, I ran composer update jic.   
*******
**My test:**
    public function playGame(AcceptanceTester $I)
    {
        $I->amOnPage('/');
        $I->fillField('[test=1pm-radio]', '1pm');
        $I->click('[test=submit-button]');
        $I->seeElement('[test=results-div]');
    }

**index.blade.php**

<input type='radio' test='1pm-radio'name='choice' value='1pm' id='1pm'>
                <label for='1pm'>1pm</label>

 <div test='results-div' class ='results'>

What am I missing?  

TIA!

Mary

**Comment by madagaluna** [comment]
This is also on the index.blade.php

 <button test='submit-button' type='submit'>BOOM!</button>
 <div test='results-div' class ='results'>

odd, when I submit the comment, it doesn't show the code.  I'll try again without the anchor brackets:

button test='submit-button' type='submit'>BOOM!</button
 div test='results-div' class ='results'

**Comment by madagaluna** [comment]
Disregard.  I found a few work arounds.  I don't know why I had the issues with my custom attributes, but there's always another way.  'form input[]' and grabAttributeFrom saved the day.  Good luck, all, and thanks for all the help along the way.  I'm finished!!!!

**Comment by susanBuck** [comment]
Congrats on wrapping things up! :-)
