### ISSUE TITLE
SSH key connection issue with DigitalOcean

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#4]
I stepped in it!  
I am using Windows

Attempt 1: went fine through the default splash page but would not connect.  I had named my SSH key when creating the droplet **hes** not **hes.pub**.  Perhaps that was the issue.
I deleted the droplet and the keys then deleted/recreated both keys, named hes again.  The config was still there so I left it.

Attempt 2: I created a new droplet and named my key hes2.pub in the digital ocean set up.  The IP address 137.184.16.139 refused to connect. I deleted the droplet

Attempt 3:  I thought the different key names may be the issue so I changed the key name to hes2.pub with bash.  Again, the IP address 165.227.193.18 refused to connect.

Attempt 4:
Deleted droplet, deleted keys using rm, recreated keys with new name, added new name to identity file, created new droplet, used name of key with .pub.  result: 143.198.164.89 refused to connect.

I am going to start from scratch, but I thought I'd through this out there/

The bash response to the first attempt was the most lengthy:
**Attempt 1**
$ ssh root@104.131.160.61
The authenticity of host '104.131.160.61 (104.131.160.61)' can't be established.
ED25519 key fingerprint is SHA256:0pub3so5xF3xhlEBd1TS0SFNr2EuazVn9gaCfv9Bshc.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '104.131.160.61' (ED25519) to the list of known hosts.
root@104.131.160.61: Permission denied (publickey).

madag@Editing MINGW64 ~/.ssh
$ ssh -v root@104.131.160.61
OpenSSH_9.4p1, OpenSSL 3.1.2 1 Aug 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to 104.131.160.61 [104.131.160.61] port 22.
debug1: Connection established.
debug1: identity file /c/Users/madag/.ssh/id_rsa type -1
debug1: identity file /c/Users/madag/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/madag/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/madag/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/madag/.ssh/id_ecdsa_sk type -1
debug1: identity file /c/Users/madag/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /c/Users/madag/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/madag/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/madag/.ssh/id_ed25519_sk type -1
debug1: identity file /c/Users/madag/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /c/Users/madag/.ssh/id_xmss type -1
debug1: identity file /c/Users/madag/.ssh/id_xmss-cert type -1
debug1: identity file /c/Users/madag/.ssh/id_dsa type -1
debug1: identity file /c/Users/madag/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
debug1: compat_banner: match: OpenSSH_8.9p1 Ubuntu-3ubuntu0.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 104.131.160.61:22 as 'root'
debug1: load_hostkeys: fopen /c/Users/madag/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: sntrup761x25519-sha512@openssh.com
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:0pub3so5xF3xhlEBd1TS0SFNr2EuazVn9gaCfv9Bshc
debug1: load_hostkeys: fopen /c/Users/madag/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '104.131.160.61' is known and matches the ED25519 host key.
debug1: Found key in /c/Users/madag/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /c/Users/madag/.ssh/id_rsa
debug1: Will attempt key: /c/Users/madag/.ssh/id_ecdsa
debug1: Will attempt key: /c/Users/madag/.ssh/id_ecdsa_sk
debug1: Will attempt key: /c/Users/madag/.ssh/id_ed25519
debug1: Will attempt key: /c/Users/madag/.ssh/id_ed25519_sk
debug1: Will attempt key: /c/Users/madag/.ssh/id_xmss
debug1: Will attempt key: /c/Users/madag/.ssh/id_dsa
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com=<0>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /c/Users/madag/.ssh/id_rsa
debug1: Trying private key: /c/Users/madag/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/madag/.ssh/id_ecdsa_sk
debug1: Trying private key: /c/Users/madag/.ssh/id_ed25519
debug1: Trying private key: /c/Users/madag/.ssh/id_ed25519_sk
debug1: Trying private key: /c/Users/madag/.ssh/id_xmss
debug1: Trying private key: /c/Users/madag/.ssh/id_dsa
debug1: No more authentication methods to try.
root@104.131.160.61: Permission denied (publickey).

**Attempt 2:**

madag@Editing MINGW64 ~/.ssh
$ ls
hes  hes.pub

madag@Editing MINGW64 ~/.ssh
$ ls -la~/.ssh
ls: unknown option -- ~
Try 'ls --help' for more information.

madag@Editing MINGW64 ~/.ssh
$ ssh -v@137.184.16.139
ssh: unknown option -- @
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface] [-b bind_address]   
           [-c cipher_spec] [-D [bind_address:]port] [-E log_file]
           [-e escape_char] [-F configfile] [-I pkcs11] [-i identity_file]    
           [-J destination] [-L address] [-l login_name] [-m mac_spec]        
           [-O ctl_cmd] [-o option] [-P tag] [-p port] [-Q query_option]      
           [-R address] [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           destination [command [argument ...]]

**Attempt 3:**
madag@Editing MINGW64 ~/.ssh
$ ssh root@165.227.193.18
root@165.227.193.18: Permission denied (publickey).

**attempt 4**
madag@Editing MINGW64 ~/.ssh
$ ls
config  hes2b  hes2b.pub

madag@Editing MINGW64 ~/.ssh
$ ssh root@143.198.164.89
The authenticity of host '143.198.164.89 (143.198.164.89)' can't be established.
ED25519 key fingerprint is SHA256:GUXjLxAF9k0ZHKbnQuTz5ILpEStLp0TcRaOU5tohalU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes 
Warning: Permanently added '143.198.164.89' (ED25519) to the list of known hosts.
no such identity: /c/Users/madag/.ssh/hes: No such file or directory
no such identity: /c/Users/madag/.ssh/hes2bcat: No such file or directory
root@143.198.164.89: Permission denied (publickey).

**Comment by susanBuck** [comment]
Hi @madagaluna - skimming through the output you shared, I noticed that of all the "will attempt key [key name]" lines, none of them listed the "hes" key. This makes me wonder if you had an issue with the step where you needed to edit your ssh config file and add the line to tell it to use the hes key. 

Can you share the contents of your computer's ssh config file so we can double check? (It's the file called 'config' in your .ssh directory)

**Comment by madagaluna** [comment]
Thank you for the quick response.  I noticed I didn't have a config in the .ssh, for the first three attempts.  Perhaps I didn't save it.

My 4th attempt, I recreated the keys and added those keys to the config. Perhaps I saved it then because now I have a config in my ssh folder.

[cid:4508e62b-e63b-4f4c-8a20-52039548bbc9]

ahhhh, but I see my problem - that darn cat:

IdentityFile ~/.ssh/hes
IdentityFile ~/.ssh/hes2bcat

I will add a new IdentityFile named hes2b and try again.  5th times a charm?

I'll post if this works out!

as an aside,   I don't know what "known_hosts" is.  I deleted that each time I've redone the keys.

Thanks,
Mary
________________________________

**Comment by susanBuck** [comment]
known_hosts keeps track of any external servers you connect to. 

You know the message that essentially asks "do you trust/want to connect to this server?" When you say yes to that it writes that servers IP address to the known_hosts file. Then the next time you connect to that server it sees the IP address recorded in known_hosts and doesn't need to ask you if you trust the server since you previously indicated you do.

You don't need to delete/edit the known_hosts file. There's no harm in deleting it either. Deleting it just means next time you connect to a previously trusted server you'd have to confirm you trust it again.

Let me know how your attempts at connecting go after addressing the SSH config file. I'll be standing by :)

**Comment by madagaluna** [comment]
I changed the name in IdentityFile to hes2b and it didn't work.  Perhaps the problem is that the .pub file is being saved as a Microsoft publisher file?

**Comment by susanBuck** [comment]
Hm this is a tricky problem to solve without seeing everything that's going on. 

Any chance you're free now to do a remote share via Zoom so we can look at this together? 

If so let me know and I'll get to a computer and send you a zoom link.

I can also be available tomorrow or Monday if either works better for you.

**Comment by madagaluna** [comment]
I am available now but my desktop does not have a camera.  Can I still share my screen?  I've never tried with this computer.

**Comment by susanBuck** [comment]
No camera necessary. Give me a few minutes and I'll send you a zoom link.

**Comment by madagaluna** [comment]
Terrific.  I'm here all night.

**Comment by susanBuck** [comment]
Ok, all set - Here's the zoom link: https://harvard.zoom.us/my/susanbuck

**Comment by susanBuck** [comment]
Issue resolved via Zoom so closing this thread. If anyone else has any problems with their SSH connections w/ DigitalOcean, let me know!
