### ISSUE TITLE
403 Forbidden error when accessing server via domain

### ISSUE THREAD

**Issue by dpurser-dev** [susanBuck/e2-fall23#5]
Hi Susan,

I am still having some trouble with my domain, which is currently returning a 403 error. I have tried the troubleshooting tips in the notes (e.g., clearing cache, accessing on a different network, etc.) but have so far been unable to access my boiler plate HTML page. However, I can access this page directly via the IP address of my server. 

Here are my DNS settings on Namecheap:
![image](https://github.com/susanBuck/e2-fall23/assets/102697521/41329dbf-1dae-4cef-894c-b02391e5bca8)

And the ping results for my domain showing the correct IP address:
![image](https://github.com/susanBuck/e2-fall23/assets/102697521/d42440f8-46da-4249-895b-f288f16f11fd)

And lastly, the current page that I see when trying to access my server via the domain:
![image](https://github.com/susanBuck/e2-fall23/assets/102697521/152ca375-5037-418a-a53d-147158f4f0bb)

Any help would be much appreciated!

Thank you,
David

**Comment by richiecarey** [comment]
Hi David,

Could be just a temporary caching issue, it's working fine for me here ...

<img width="544" alt="Screenshot 2023-09-19 at 3 31 21 PM" src="https://github.com/susanBuck/e2-fall23/assets/8711204/4d8d88f1-bd02-4c0c-aab7-9792aeacac77">

**Comment by susanBuck** [comment]
I can confirm it's also working on my end. Is it still not loading for you, @dpurser-dev ?

**Comment by AlexCosta2023** [comment]
> Hi David,
> 
> Could be just a temporary caching issue, it's working fine for me here ...
> 

Definitely a caching issue. It's working on my end.
Hey @richiecarey -- just noticed you!

**Comment by dpurser-dev** [comment]
Thanks team! It's working for me now too. I appreciate the quick responses.
