### ISSUE TITLE
Copied bank.php code not displaying on web

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#6]
I'm here to normalize asking questions!

I copied the bank.php code into the practice folder on remote desktop in VSC. 
e2practice.timberthedestroyer.xyz displays correctly but e2practice.timberthedestroy.xyz/bank.php does not display (404 error).
I committed and synced the bank.php code
The bank.php is not in github **UPDATE: it is now displaying in Github**
Under account I am logged into Github and the settings sync is on

I added a test.html file and it also does not display.

SSH: hes-on-DigitalOcean is in the bottom left hand corner.  

It's kind of hard to mess this up.  Any thoughts on what be going on?  I'll watch error reporting now but I don't think it will deal with this kind of issue.

Thanks in advance!
Mary

**Comment by susanBuck** [comment]
Hi Mary - 👍 to normalizing asking questions! : ) I'm taking a look at your server right now to see what the issue is and will report back shortly.

**Comment by susanBuck** [comment]
It looks like <http://e2practice.timberthedestroyer.xyz> loads, but it’s displaying the main index page at `/var/www/e2/index.php` when it should be displaying `/var/www/e2/practice/index.php`.

I took a look at your sites config file (`/etc/nginx/sites-available/hes`) to see why and see you have a single config for your p1 site (<http://e2p1.timberthedestroyer.xyz>):

```
server {

    listen 80;
    server_name e2p1.timberthedestroyer.xyz;
    root /var/www/e2/p1/;

    index index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

You need to have a separate config in this same file for the e2practice subdomain. You can have multiple config blocks in that site config file for each subdomain you want to configure.

For comparison, here's what my site config file looks like:

```
server {
    listen 80;
    server_name e2practice.hesweb.xyz;
    root /var/www/e2/practice/;

    index index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

server {
    listen 80;
    server_name e2p1.hesweb.xyz;
    root /var/www/e2/p1/;

    index index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

**Comment by madagaluna** [comment]
Terrific.  Thank you.  Great review of adding folders/pages to the config.  I didn't realize I needed to do that
