### ISSUE TITLE
For loop syntax in notes will not run

### ISSUE THREAD

**Issue by dpurser-dev** [susanBuck/e2-fall23#7]
Hi Susan,

I might be jumping ahead here, but I am trying to execute the "for" loop in the notes regarding the Separation of Concerns ([here](https://hesweb.dev/e2/notes/php/separation-of-concerns))

Unfortunately, I can't get your for loop with this syntax to execute:
```
<ul>
    <?php for($coin in $coins) { ?>
        <li><?php echo $coin; ?></li>
    <?php } ?>
</ul>

```
Looking at the PHP documentation, it would appear that the "foreach" syntax should be used:
```
<?php
$arr = array(1, 2, 3, 4);
foreach ($arr as &$value) {
    $value = $value * 2;
}
// $arr is now array(2, 4, 6, 8)
unset($value); // break the reference with the last element
?>

```
However, I prefer the syntax you have used because it is more similar to Python - is there something that I should do differently to get it to run?

Thanks!

**Comment by susanBuck** [comment]
Hi @dpurser-dev - You've discovered a bug in the notes. That's what I get for not testing hypothetical code examples. :-) It should be `foreach`, which is used to loop through arrays. PHP does have a `for` loop but it's for numerical iteration - e.g. start at x, go to y, etc.

I'll update the notes. Thanks for observing this!

**Comment by dpurser-dev** [comment]
Thanks Susan, that makes sense!
