### ISSUE TITLE
Question 2 week4 Foreach loop

### ISSUE THREAD

**Issue by anp2937** [susanBuck/e2-fall23#8]
I did not find optimal way how to use **foreach** loop together with **if** condition to solve the problem.
Tried different approaches but almost all of them using **while** loop.

I assume that in order to use **foreach** loop that will go through every $card element we will need to add additional **$flag** variable that will be a trigger to decide when we assign current value to **player** or **dealer**.

Am I missing something? It would be great to see some examples after all students done with this assignment.

Thanks

**Comment by susanBuck** [comment]
Hi @anp2937 - You are correct that the foreach approach could use a flag to keep track of who is dealt to.

I'll be sharing several solutions/examples in this week’s upcoming lecture, but if you want a sneak peak, [here is the code...](https://gist.github.com/susanBuck/3a92feae1badfcb98247ed95d8dfa4bc)

**Comment by anp2937** [comment]
Thank you!
