### ISSUE TITLE
Week 3 Assignment, Question 4 correct answer issue

### ISSUE THREAD

**Issue by dpurser-dev** [susanBuck/e2-fall23#9]
Hi Susan,

Question 4 of the Week 3 assignment asks: **Which of the following file types would support both PHP and HTML code?**

Apparently, the correct answer is **only PHP**

However, HTML file types can support both HTML and PHP code. As a result, I would like to argue that the correct answer to this questions include **HTML**

Source: https://www.geeksforgeeks.org/how-to-embed-php-code-in-an-html-page/

Example code:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
   <HEAD>
      <TITLE>Testing Weather Data</TITLE>
   </HEAD>
   <BODY>
      <div id="weather">
         <p>Weather Information
         <?php include "/home/tahoang/Desktop/weatherData.php"; ?>
      </div>
   </BODY>
</HTML>
```

**Comment by susanBuck** [comment]
Hi @dpurser-dev -

HTML files can sometimes process PHP but only if a server-level configuration has been made allowing them to do so. More commonly, HTML files will not actually process PHP but will instead encode it as a comment or even output it to the page as plain text. 

An example of this can be seen on our servers. Here's a .html file I made with some PHP code included: <http://e2practice.hesweb.xyz/test.html>

Note how the expected PHP is not processed. If you do "View Source" in your browser you’ll see the PHP code was not processed but instead treated as a comment.

By default, PHP files will always process PHP (and HTML). 

If this were a "select all that apply" type question I might accept HTML as an answer, but given only one answer is accepted, PHP is the more appropriate answer, especially as that was what was demonstrated in lecture and is cited in the notes: 

> "A .php file can contain both HTML code and PHP code." -[ref](https://hesweb.dev/e2/notes/php/syntax#the-basics)

Hope that clarifies things. If you have any follow-up questions on this, let me know.

**Comment by dpurser-dev** [comment]
Hi @susanBuck -

Thanks for the quick response, that makes sense. 

I think I found this question a bit confusing because, in this course, we are taught to configure our servers such that they process PHP embedded in HTML code. Having not been exposed to PHP before (and therefore 100% of my understanding of PHP originates from this course), I was under the impression this is industry standard and therefore normal behavior for all servers.

**Comment by susanBuck** [comment]
> we are taught to configure our servers such that they process PHP embedded in HTML code

Yes, we write PHP code embedded in HTML code but you were instructed to do it in a .php file. I'm not sure how this translates to .html files being the better answer. 

If there are any future confusions like this on a question, feel free to send me an email when completing the assignment for further clarification. Always happy to discuss!
